package ch.so.agi.netl;

import java.util.Map;
import org.springframework.ai.mcp.annotation.McpTool;
import org.springframework.ai.mcp.annotation.McpToolParam;
import org.springframework.stereotype.Component;

@Component
public class JobTools {
    private final JobService service;
    public JobTools(JobService service) { this.service=service; }
    @McpTool(name="job_context",description="Read models, catalog and GRETL job conventions. Read only.",annotations=@McpTool.McpAnnotations(readOnlyHint=true,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> context(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme) { return service.call("context",theme,null,null); }
    @McpTool(name="job_validate",description="Validate job artifacts without executing Gradle; returns exact expectationsRevision for user review.",annotations=@McpTool.McpAnnotations(readOnlyHint=true,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> validate(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job) { return service.call("validate",theme,job,null); }
    @McpTool(name="job_confirm",description="Freeze exact expectationsRevision ONLY after explicit user confirmation of displayed fixtures and expected results. Never self-approve LLM expectations.",annotations=@McpTool.McpAnnotations(readOnlyHint=false,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> confirm(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job, @McpToolParam(required=true,description="expectationsRevision") String expectationsRevision) { return service.call("confirm",theme,job,expectationsRevision); }
    @McpTool(name="job_test",description="Run isolated synthetic fixture tests and repeated real Gradle transfer. Serial only. Never retry BUSY/timeouts. At most three changed-job attempts after ordinary failure.",annotations=@McpTool.McpAnnotations(readOnlyHint=false,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> test(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job) { return service.call("test",theme,job,null); }
    @McpTool(name="job_plan",description="Plan local edit-to-pub replacement after exact passing test. Does not transfer data; returns one-use token.",annotations=@McpTool.McpAnnotations(readOnlyHint=false,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> plan(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job) { return service.call("plan",theme,job,null); }
    @McpTool(name="job_run",description="Execute local job once. Requires explicit local transfer request and one-use token. Post-commit assertion failure does NOT roll back. Never auto-retry.",annotations=@McpTool.McpAnnotations(readOnlyHint=false,destructiveHint=true,openWorldHint=false))
    public Map<String,Object> run(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job, @McpToolParam(required=true,description="planToken") String planToken) { return service.call("run",theme,job,planToken); }
    @McpTool(name="job_status",description="Read recorded job checks and whether their fingerprint is current.",annotations=@McpTool.McpAnnotations(readOnlyHint=true,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> status(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job) { return service.call("status",theme,job,null); }
    @McpTool(name="job_write_transform",description="Write only job.json, build.gradle or sql/*.sql in selected theme job. Cannot change fixtures or assertions.",annotations=@McpTool.McpAnnotations(readOnlyHint=false,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> write_transform(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job, @McpToolParam(required=true,description="file") String file, @McpToolParam(required=true,description="content") String content) { return service.write(theme,job,file,content,false); }
    @McpTool(name="job_write_test",description="Write only tests.json, fixtures/*.sql or assertions/*.sql. Confirmed expectations are immutable; use a new job for changed requirements.",annotations=@McpTool.McpAnnotations(readOnlyHint=false,destructiveHint=false,openWorldHint=false))
    public Map<String,Object> write_test(@McpToolParam(required=true,description="Exact theme identifier amt/thema from user request, e.g. tests/job_smoke_123. Never substitute demo/standorte.") String theme, @McpToolParam(required=true,description="Job directory identifier only, e.g. transfer. Not the theme name, not a schema name.") String job, @McpToolParam(required=true,description="file") String file, @McpToolParam(required=true,description="content") String content) { return service.write(theme,job,file,content,true); }
}
