spring.main.web-application-type=none
spring.main.banner-mode=off
spring.ai.mcp.server.name=netl-mcp
spring.ai.mcp.server.version=0.1.0
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.request-timeout=180s
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
logging.level.root=WARN
