spring.profiles.default=stdio
spring.main.banner-mode=off
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=netl-mcp
spring.ai.mcp.server.version=${mcpServerVersion}
spring.ai.mcp.server.request-timeout=180s
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
spring.ai.mcp.server.capabilities.completion=false
logging.level.root=WARN
